### ISSUE TITLE
EWRL organization name

### ISSUE THREAD

**Issue by erachelson** [erachelson/ewrl_temp#1]
Dear @Ewrl ,
I'm the general chair of the 2024 European Workshop on Reinforcement Learning (EWRL) and would have liked to use the organization name on github. I see that you have had little use of your github username. Would you be willing to hand it over to the RL research community?
Best,
Emmanuel

**Comment by Ewrl** [comment]
While that's true that I haven't used GitHub much, I'd like to note that I am planning to use it in the future. I've been using this name for quite a long time and don't see myself changing it anytime soon. However I don't see a problem in You using a word "EWRL" in Your organization name. If You'd like, You can use it - just not "Ewrl" as it is already taken by me. I'll let you know if I change my mind and hope that's not too big of a problem for You. I apologize for not agreeing.
Best regards.

**Comment by erachelson** [comment]
Thank you for this quick answer. I wish I could make you change your mind (especially since EWRL has been a worldwide research workshop for more than 30 years) but I respect your decision.
Best,
